services:
  node-1:
    build: ./
    container_name: sridhar-node-1
    environment:
      NODE_ID: node-1
      VLLM_URL: http://host.docker.internal:8000
    ports:
      - "8001:8000"
    networks:
      - decentralized-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node-2:
    build: ./
    container_name: sridhar-node-2
    environment:
      NODE_ID: node-2
      VLLM_URL: http://host.docker.internal:8000
    ports:
      - "8002:8000"
    networks:
      - decentralized-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node-3:
    build: ./
    container_name: sridhar-node-3
    environment:
      NODE_ID: node-3
      VLLM_URL: http://host.docker.internal:8000
    ports:
      - "8003:8000"
    networks:
      - decentralized-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  decentralized-net:
    driver: bridge